# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cyokine_array.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 230)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.databutton = QtWidgets.QPushButton(self.centralwidget)
        self.databutton.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.databutton.setObjectName("databutton")
        self.datalabel = QtWidgets.QLabel(self.centralwidget)
        self.datalabel.setGeometry(QtCore.QRect(110, 40, 121, 41))
        self.datalabel.setObjectName("datalabel")
        self.namesbutton = QtWidgets.QPushButton(self.centralwidget)
        self.namesbutton.setGeometry(QtCore.QRect(10, 120, 101, 23))
        self.namesbutton.setObjectName("namesbutton")
        self.nameslabel = QtWidgets.QLabel(self.centralwidget)
        self.nameslabel.setGeometry(QtCore.QRect(120, 120, 121, 21))
        self.nameslabel.setObjectName("nameslabel")
        self.runbutton = QtWidgets.QPushButton(self.centralwidget)
        self.runbutton.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.runbutton.setObjectName("runbutton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 10, 191, 31))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 369, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.databutton.setText(_translate("MainWindow", "Load data file"))
        self.datalabel.setText(_translate("MainWindow", "No data file found"))
        self.namesbutton.setText(_translate("MainWindow", "Load names file"))
        self.nameslabel.setText(_translate("MainWindow", "No names file found"))
        self.runbutton.setText(_translate("MainWindow", "Run"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter Filename</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
